{{- if .Values.ingress.create -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-loki
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  # tls:
  #   - hosts:
  #     - {{ .Values.ingress.hosts | toYaml }}
  #     # This assumes tls-secret exists and the SSL
  #     # certificate contains a CN for foo.bar.com
  #     secretName: tdg-int-net-cert
  defaultBackend:
    service:
      name: loki-loki-distributed-gateway
      port:
        number: 80
  rules:
  - host: {{ .Values.ingress.hosts | toYaml }}
    http:
      paths:
      - pathType: Prefix
        path: "/*"
        backend:
          service:
            name: loki-loki-distributed-gateway
            port:
              number: 80
{{- end -}}