apiVersion: v1
kind: Secret
metadata:
  name: loki-access-gcs
  namespace: loki
type: Opaque
data:
  key.json: <path:projects/362159383816/secrets/google_credentials_devops_cicd#google_credentials_devops_cicd | base64encode>
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tdg-int-net-cert
data:
  tls.crt: <path:projects/362159383816/secrets/tdg_int_tls_crt#tdg_int_tls_crt | base64encode>
  tls.key: <path:projects/362159383816/secrets/tdg_int_tls_key#tdg_int_tls_key | base64encode>