apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  project: nginx-ingress
  source:
    repoURL: 'https://helm.nginx.com/stable'
    targetRevision: 0.15.1
    chart: nginx-ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true