{{- if .Values.vaultProfiles.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-vault-profiles
data:
  {{- range .Values.vaultProfiles.profiles }}
  {{ .filename }}: |
    {{- .value | nindent 4}}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: tdg-int-net-cert
data:
  tls.crt: <path:projects/362159383816/secrets/tdg_int_tls_crt#tdg_int_tls_crt | base64encode>
  tls.key: <path:projects/362159383816/secrets/tdg_int_tls_key#tdg_int_tls_key | base64encode>