{
 "title": "Cluster Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "pod restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total"
    }
   ]
  },
  {
   "title": "Memory Node left",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 8 },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  }
 ]
}